### PR TITLE
browser plugin

### PR DESCRIPTION
**Pull request by SorenHolstHansen**
Thanks a lot for a very cool crate! I added the support for the browser plugin. Let me know if anything looks wrong

### CODE REVIEW

**Comment by wainwrightmark** [comment]
Just reading the code it all looks fine. I will confirm it works one some real devices tomorrow and then merge. Well done for figuring out how to do this - I realize I didn't document that crate super well.

**Comment by SorenHolstHansen** [comment]
Nice! I think it was relatively easy reading the README, though it would have been nice with a setup guide

**Comment by SorenHolstHansen** [comment]
Could I possibly convince you to make a new release? @wainwrightmark  :)

**Comment by wainwrightmark** [comment]
> Could I possibly convince you to make a new release? @wainwrightmark :)

I will do it as soon as I can - I have been meaning to but I'm having a bit of an intense week with an app launch coming up.

**Comment by SorenHolstHansen** [comment]
> > Could I possibly convince you to make a new release? @wainwrightmark :)
> 
> I will do it as soon as I can - I have been meaning to but I'm having a bit of an intense week with an app launch coming up.

No worries, you just do it when you get the time

**Comment by wainwrightmark** [comment]
Ok. I have released 0.11.0 Sorry for the delay and thanks for the contribution.

**Comment by SorenHolstHansen** [comment]
Thanks a lot!

**Pull request merged**
